CREATE TABLE IF NOT EXISTS colorado_soc_tier (soc VARCHAR, occupation_title VARCHAR, tier VARCHAR);
CREATE INDEX IF NOT EXISTS colorado_soc_tier_idx_0 ON colorado_soc_tier(soc);
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('SOC Code', 'Occupation Title', 'Tier Classification');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1071', 'Human Resources Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1081', 'Logisticians', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1082', 'Project Management Specialists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1111', 'Management Analysts', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1121', 'Meeting, Convention, and Event Planners', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1151', 'Training and Development Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-1161', 'Market Research Analysts and Marketing Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2011', 'Accountants and Auditors', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2051', 'Financial and Investment Analysts', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2052', 'Personal Financial Advisors', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2061', 'Financial Examiners', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2071', 'Credit Counselors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('13-2082', 'Tax Preparers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1211', 'Computer Systems Analysts', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1212', 'Information Security Analysts', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1231', 'Computer Network Support Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1232', 'Computer User Support Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1241', 'Computer Network Architects', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1242', 'Database Administrators', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1243', 'Database Architects', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1252', 'Software Developers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1253', 'Software Quality Assurance Analysts and Testers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1254', 'Web Developers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-1255', 'Web and Digital Interface Designers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-2011', 'Actuaries', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-2031', 'Operations Research Analysts', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-2041', 'Statisticians', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('15-2051', 'Data Scientists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-1011', 'Architects, Except Landscape and Naval', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-1021', 'Cartographers and Photogrammetrists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-1022', 'Surveyors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2011', 'Aerospace Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2041', 'Chemical Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2051', 'Civil Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2061', 'Computer Hardware Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2071', 'Electrical Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2072', 'Electronics Engineers, Except Computer', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2081', 'Environmental Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2112', 'Industrial Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2131', 'Materials Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2141', 'Mechanical Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-2171', 'Petroleum Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-3022', 'Civil Engineering Technologists and Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-3025', 'Environmental Engineering Technologists and Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('17-3031', 'Surveying and Mapping Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1012', 'Food Scientists and Technologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1013', 'Soil and Plant Scientists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1021', 'Biochemists and Biophysicists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1022', 'Microbiologists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1023', 'Zoologists and Wildlife Biologists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1031', 'Conservation Scientists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1041', 'Epidemiologists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-1042', 'Medical Scientists, Except Epidemiologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-2012', 'Physicists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-2021', 'Atmospheric and Space Scientists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-2041', 'Environmental Scientists and Specialists, Including Health', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-2042', 'Geoscientists, Except Hydrologists and Geographers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-2043', 'Hydrologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-3033', 'Clinical and Counseling Psychologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-3034', 'School Psychologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-3051', 'Urban and Regional Planners', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-4021', 'Biological Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-4031', 'Chemical Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-4042', 'Environmental Science and Protection Technicians, Including Health', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-4043', 'Geological Technicians, Except Hydrologic Technicians', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-4092', 'Forensic Science Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-5011', 'Occupational Health and Safety Specialists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('19-5012', 'Occupational Health and Safety Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1012', 'Educational, Guidance, and Career Counselors and Advisors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1013', 'Marriage and Family Therapists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1015', 'Rehabilitation Counselors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1018', 'Substance Abuse, Behavioral Disorder, and Mental Health Counselors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1021', 'Child, Family, and School Social Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1022', 'Healthcare Social Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1023', 'Mental Health and Substance Abuse Social Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1092', 'Probation Officers and Correctional Treatment Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1093', 'Social and Human Service Assistants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-1094', 'Community Health Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('21-2011', 'Clergy', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('23-1011', 'Lawyers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('23-1023', 'Judges, Magistrate Judges, and Magistrates', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('23-2011', 'Paralegals and Legal Assistants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1011', 'Business Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1021', 'Computer Science Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1022', 'Mathematical Science Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1032', 'Engineering Teachers, Postsecondary', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1042', 'Biological Science Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1051', 'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1052', 'Chemistry Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1065', 'Political Science Teachers, Postsecondary', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1066', 'Psychology Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1071', 'Health Specialties Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1072', 'Nursing Instructors and Teachers, Postsecondary', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1081', 'Education Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1111', 'Criminal Justice and Law Enforcement Teachers, Postsecondary', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1121', 'Art, Drama, and Music Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1122', 'Communications Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1123', 'English Language and Literature Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1124', 'Foreign Language and Literature Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1125', 'History Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-1126', 'Philosophy and Religion Teachers, Postsecondary', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2012', 'Kindergarten Teachers, Except Special Education', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2021', 'Elementary School Teachers, Except Special Education', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2022', 'Middle School Teachers, Except Special and Career/Technical Education', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2031', 'Secondary School Teachers, Except Special and Career/Technical Education', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2032', 'Career/Technical Education Teachers, Secondary School', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2051', 'Special Education Teachers, Preschool', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2052', 'Special Education Teachers, Kindergarten and Elementary School', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2057', 'Special Education Teachers, Middle School', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-2058', 'Special Education Teachers, Secondary School', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-4012', 'Curators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-4022', 'Librarians and Media Collections Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('25-9031', 'Instructional Coordinators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-1025', 'Interior Designers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-2022', 'Coaches and Scouts', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-3042', 'Technical Writers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-3091', 'Interpreters and Translators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-4011', 'Audio and Video Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('27-4031', 'Camera Operators, Television, Video, and Film', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1011', 'Chiropractors', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1031', 'Dietitians and Nutritionists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1051', 'Pharmacists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1071', 'Physician Assistants', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1122', 'Occupational Therapists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1123', 'Physical Therapists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1126', 'Respiratory Therapists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1127', 'Speech-Language Pathologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1131', 'Veterinarians', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1141', 'Registered Nurses', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1151', 'Nurse Anesthetists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-1171', 'Nurse Practitioners', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2010', 'Clinical Laboratory Technologists and Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2031', 'Cardiovascular Technologists and Technicians', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2032', 'Diagnostic Medical Sonographers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2034', 'Radiologic Technologists and Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2035', 'Magnetic Resonance Imaging Technologists', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2043', 'Paramedics', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2052', 'Pharmacy Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2053', 'Psychiatric Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2055', 'Surgical Technologists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-2072', 'Medical Records Specialists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-9021', 'Health Information Technologists and Medical Registrars', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('29-9091', 'Athletic Trainers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-1133', 'Psychiatric Aides', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-2011', 'Occupational Therapy Assistants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-2021', 'Physical Therapist Assistants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-9011', 'Massage Therapists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-9092', 'Medical Assistants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-9093', 'Medical Equipment Preparers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('31-9097', 'Phlebotomists', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('33-1012', 'First-Line Supervisors of Police and Detectives', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('33-1021', 'First-Line Supervisors of Firefighting and Prevention Workers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('33-2011', 'Firefighters', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('33-3051', 'Police and Sheriff''s Patrol Officers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('35-1011', 'Chefs and Head Cooks', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('35-1012', 'First-Line Supervisors of Food Preparation and Serving Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('37-2021', 'Pest Control Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('37-3012', 'Pesticide Handlers, Sprayers, and Applicators, Vegetation', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('39-1014', 'First-line Supervisors of Entertainment And Recreation Workers, Except Gambling Services', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('39-9031', 'Exercise Trainers and Group Fitness Instructors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('41-3041', 'Travel Agents', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('41-3091', 'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('41-4011', 'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('41-9031', 'Sales Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('43-4031', 'Court, Municipal, and License Clerks', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('43-4181', 'Reservation and Transportation Ticket Agents and Travel Clerks', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('43-5011', 'Cargo and Freight Agents', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('43-5031', 'Public Safety Telecommunicators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2042', 'Floor Layers, Except Carpet, Wood, and Hard Tiles', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2044', 'Tile and Stone Setters', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2081', 'Drywall and Ceiling Tile Installers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2111', 'Electricians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2121', 'Glaziers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2221', 'Structural Iron and Steel Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-2231', 'Solar Photovoltaic Installers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-4051', 'Highway Maintenance Workers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-4071', 'Septic Tank Servicers and Sewer Pipe Cleaners', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-5011', 'Derrick Operators, Oil and Gas', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-5012', 'Rotary Drill Operators, Oil and Gas', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-5013', 'Service Unit Operators, Oil and Gas', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('47-5071', 'Roustabouts, Oil and Gas', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-2011', 'Computer, Automated Teller, and Office Machine Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-2021', 'Radio, Cellular, and Tower Equipment Installers and Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-2022', 'Telecommunications Equipment Installers and Repairers, Except Line Installers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-2097', 'Audiovisual Equipment Installers and Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-2098', 'Security and Fire Alarm Systems Installers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-3011', 'Aircraft Mechanics and Service Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-3041', 'Farm Equipment Mechanics and Service Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-3092', 'Recreational Vehicle Service Technicians', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9011', 'Mechanical Door Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9021', 'Heating, Air Conditioning, and Refrigeration Mechanics and Installers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9041', 'Industrial Machinery Mechanics', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9043', 'Maintenance Workers, Machinery', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9052', 'Telecommunications Line Installers and Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('49-9062', 'Medical Equipment Repairers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('51-8021', 'Stationary Engineers and Boiler Operators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('51-9162', 'Computer Numerically Controlled Tool Programmers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-1041', 'Aircraft Cargo Handling Supervisors', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-2011', 'Airline Pilots, Copilots, and Flight Engineers', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-2012', 'Commercial Pilots', '1');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-2031', 'Flight Attendants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-3033', 'Light Truck Drivers', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-3051', 'Bus Drivers, School', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-3052', 'Bus Drivers, Transit and Intercity', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-6032', 'Aircraft Service Attendants', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-7051', 'Industrial Truck and Tractor Operators', '2');
INSERT INTO colorado_soc_tier (soc, occupation_title, tier) VALUES ('53-7081', 'Refuse and Recyclable Material Collectors', '2');
