version: "3"

services:
  db:
    build: db/.
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  ben:
     build: ben/.
     ports:
       - "8200:8200"
     depends_on:
       - db
  gui:
     image: httpd:latest
     volumes:       
       - d:/r/local/dev/github/sandbox/products/improvekata/gui/improvekatagui/src/simple:/usr/local/apache2/htdocs
     ports:
       - "8210:80"
