version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./reverse/conf:/etc/nginx
      - ./reverse/monitor:/html/monitor
    depends_on:
      - db
      - ben
      - gui
  db:
    build: db/.
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  ben:
     build: ben/.
     depends_on:
       - db
  gui:
     image: httpd:latest
     volumes:
       - ./gui/improvekatagui/src/simple:/usr/local/apache2/htdocs
     depends_on:
       - ben
