pipeline {
    agent any
    stages {
        stage('Handshake & setup') {
            steps {
                sh 'echo Starting the job. Working directory is `pwd`'
                dir('./docker/mod11qaautomation/fakeresponse') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew wrapper'
                }
            }
        }
        stage('Is docker there') {
            steps {
                sh 'echo ============= output from docker ================= '
                sh 'docker ps'
            }
        }
        stage('Build') {
            steps {
                dir('./docker/mod11qaautomation/fakeresponse') {
                    sh './gradlew assemble'
                }
            }
        }
        stage('Create jar') {
            steps {
                dir('./docker/mod11qaautomation/fakeresponse') {
                    sh './gradlew bootJar'
                }
            }
        }
        stage('Build Docker image') {
            steps {
                dir('./docker/mod11qaautomation/fakeresponse') {
                    sh './gradlew docker'
                    //sh 'docker build --tag fakeresponse .'
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                dir('./docker/mod11qaautomation/fakeresponse') {
                    sh 'docker rm -f fakeresponse'
                    sh './gradlew dockerRun'
                    //sh 'docker run -d --rm --name fakeresponse -p 8086:8080 fakeresponse'
                }
            }
        }
    }
}
